spring.application.name=Elearning
spring.datasource.url=jdbc:mysql://localhost:3306/elearning
spring.datasource.username=springuser
spring.datasource.password=AvnEesh@3512
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
