spring.application.name=Elearning
spring.datasource.url=jdbc:mysql://localhost:3306/elearning
spring.datasource.username=springuser
spring.datasource.password=AvnEesh@3512
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
stripe.secret.key=${STRIPE_SECRET_KEY}
cloudinary.cloud-name=cn1ahgqo
cloudinary.api-key=357956147158239
cloudinary.api-secret=v-37vKtCqdRFsWRLCXJT_eZl5C8